### ISSUE TITLE
Incompatibility with latest rootpy versions?

### ISSUE THREAD

**Issue by gbesjes** [ndawe/tmva2bin#1]
Hi @ndawe ,

I'm trying to create a bin file from several TMVA XMLs, but the categories I'm defining can't be parsed:

    tmva2bin -c "{TAU_ABSDELTAETA:F|1.37,2,2.3}x{numTrack:I|1}" -f "bin" -o "/tmp/test.bin" /Users/gbesjes/work/taueleBDT.training/workdir/161021.tauEleBDT.new.vars/1P/barrel/tauEleBDT_optB.xml /Users/gbesjes/work/taueleBDT.training/workdir/161021.tauEleBDT.new.vars/1P/barrel/tauEleBDT_optB.xml

    Traceback (most recent call last):
      File "/Users/gbesjes/Library/Python/2.7/bin/tmva2bin", line 5, in <module>
        pkg_resources.run_script('tmva2bin==1.0', 'tmva2bin')
      File "/usr/local/lib/python2.7/site-packages/distribute-0.6.28-py2.7.egg/pkg_resources.py", line 499, in run_script
        self.require(requires)[0].run_script(script_name, ns)
      File "/usr/local/lib/python2.7/site-packages/distribute-0.6.28-py2.7.egg/pkg_resources.py", line 1239, in run_script
        execfile(script_filename, namespace, namespace)
      File "/Users/gbesjes/Library/Python/2.7/lib/python/site-packages/tmva2bin-1.0-py2.7.egg/EGG-INFO/scripts/tmva2bin", line 60, in <module>
        categoryTree = Node.from_string(args.categories)
      File "/Users/gbesjes/Library/Python/2.7/lib/python/site-packages/tmva2bin-1.0-py2.7.egg/tmva2bin/decisiontree.py", line 22, in from_string
        tree = super(Node, cls).from_string(string)
      File "/usr/local/lib/python2.7/site-packages/rootpy/tree/categories.py", line 40, in from_string
        node = cls.from_string(categorymatch.group('left'), variables)
    TypeError: from_string() takes exactly 2 arguments (3 given)

I'm on rootpy 0.8.3. Is there a simple way that I can fix it? Parsing the category string using Categories.from_string() works without trouble.

**Comment by gbesjes** [comment]
The problem seems to lie inside rootpy, where these lines can be fixed:

    39         if categorymatch:
    40             node = Categories.from_string(categorymatch.group('left'), variables)
    41             subtree = Categories.from_string(categorymatch.group('right'), variables)

otherwise, Node.from_string would be called. Of course this is ugly - but the point is that at this stage in the rootpy.tree.Categories class, the correct (i.e. not the inherited) from_string method needs to be called.

**Comment by ndawe** [comment]
You're right. I'm fixing this in rootpy now. It should be Categories instead of cls.

**Comment by ndawe** [comment]
Should be fixed with rootpy/rootpy#720

**Comment by ndawe** [comment]
Glad to see this package is still useful!

**Comment by ndawe** [comment]
Fix has been merged into rootpy. Closing here. Thanks for reporting!
